acme_poc_home:
    pattern:  /
    defaults: { _controller: AcmePocBundle:Index:index }

acme_poc_profile:
    pattern:  /profile
    defaults: { _controller: AcmePocBundle:Index:profile }

acme_poc_photos:
    pattern:  /photos
    defaults: { _controller: AcmePocBundle:Index:photos }

acme_poc_uploader:
    pattern:  /upload
    defaults: { _controller: AcmePocBundle:Uploader:uploader }

acme_poc_upload_post:
    pattern:  /upload/post
    defaults: { _controller: AcmePocBundle:Uploader:post }
    
acme_poc_form:
    pattern:  /form
    defaults: { _controller: AcmePocBundle:Form:index }
    
acme_poc_form_validate:
    pattern:  /ajax/validate/photo
    defaults: { _controller: AcmePocBundle:Form:validate, _format: json }