acme_poc_home:
    pattern:  /
    defaults: { _controller: AcmePocBundle:Index:index }

acme_poc_profile:
    pattern:  /profile
    defaults: { _controller: AcmePocBundle:Index:profile }

acme_poc_photos:
    pattern:  /photos
    defaults: { _controller: AcmePocBundle:Index:photos }